myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from sistema.views import Home
from django.conf.urls.static import static
from django.conf import settings    
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,logout
from usuario.views import Login, logoutUsuario

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sistema/',include(('sistema.urls','sistema'))),
    path("mensajeria/",include(('mensajeria.urls','mensajeria'))),
    path('Home/',Home,name = 'home'),
    path('accounts/login/', Login.as_view(), name='login'),
    path('accounts/logout/', login_required(logoutUsuario), name='logout'),
    path('accounts/', include('accounts.urls')), # new
    path('accounts/', include('django.contrib.auth.urls')),

]

myproject/sistema/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('crearTipo_Reunion/',crearTipo_Reunion,name='crearTipo_Reunion'),
    path('editarTipo_Reunion/<int:id_tipo_reunion>',editarTipo_Reunion,name='editarTipo_Reunion'),
    path('listarTipo_Reunion/',listarTipo_Reunion, name='listarTipo_Reunion'),
    path('eliminarTipo_Reunion/<int:id_tipo_reunion>',eliminarTipo_Reunion,name='eliminarTipo_Reunion'),
    path('crearReunion/',crearReunion,name='crearReunion'),
    path("listarReunion/", listarReunion, name='listarReunion'),
    path('editarReunion/<int:id_reunion>',editarReunion,name='editarReunion'),
    path('eliminarReunion/<int:id_reunion>',eliminarReunion,name='eliminarReunion'),
    path('agregarAsistencia/',agregarAsistencia,name='agregarAsistencia'),
    path('agregarEncuesta/',agregarEncuesta,name ='agregarEncuesta'),
    path('agregarPregunta/',agregarPregunta,name='agregarPregunta'),
    path('agregarRespuesta/',agregarRespuesta,name='agregarRespuesta'),
    path('agregarRespuestaReunion/<int:id_encuesta>',agregarRespuestaReunion,name='agregarRespuestaReunion'),
    path('crearGrupo/',crearGrupo, name='crearGrupo'),
    path('listarGrupo/',listarGrupo,name='listarGrupo'),
    path('editarGrupo/<int:id_grupo>',editarGrupo,name='editarGrupo'),
    path('eliminarGrupo/<int:id_grupo>',eliminarGrupo,name='eliminarGrupo'),
    path('crearMiembro/',crearMiembro,name='crearMiembro'),
    path('listarMiembro/',listarMiembro,name='listarMiembro'),
    path('editarMiembro/<int:dni>',editarMiembro,name='editarMiembro'),
    path('eliminarMiembro/<int:dni>',eliminarMiembro, name='eliminarMiembro'),
    path("validarMiembro/", validarMiembro, name="validarMiembro"),
    path('reactivarMiembro/<int:dni>',reactivarMiembro, name='reactivarMiembro'),
    path("localidadesList/", localidadesList, name="localidadesList"),
    path("barriosList/", barriosList, name="barriosList"),
    path("AsistenciaTable/", AsistenciaTable, name="AsistenciaTable"),
    path("GrupoTable/", GrupoTable, name="GrupoTable"),
    path("validarGrupo/", validarGrupo, name="validarGrupo"),
    path("miembroTable/", miembroTable, name="miembroTable"),
    path("sexoList/", sexoList, name="sexoList"),
    path("configuracion/", configuracion, name="configuracion"),
    path("auditoriaMiembro/", auditoriaMiembro, name="auditoriaMiembro"),
    path("auditoriaReunion/", auditoriaReunion, name="auditoriaReunion"),
    path("auditoriaAsistencia/", auditoriaAsistencia, name="auditoriaAsistencia"),
    path("auditoriaUsuario/", auditoriaUsuario, name="auditoriaUsuario"),
    path("verAsistencia/",verAsistencia,name="verAsistencia"),
    path("EncuestaTable/", EncuestaTable, name="EncuestaTable"),
    path("crearRol/", crearRol, name="crearRol"),
    path("verRol/", verRol, name="verRol"),
    path("editarRol/<int:id_rol>", editarRol, name="editarRol"),
    path("eliminarRol/<int:id_rol>", eliminarRol, name="eliminarRol"),
    path("validarRol/", validarRol, name="validarRol"),
    path("validarPregunta/", validarPregunta, name="validarPregunta"),
    path("eliminarPregunta/<int:id_pregunta>",eliminarPregunta, name="eliminarPregunta"),
    path("opcionesList/", opcionesList, name="opcionesList"),
    path("verRespuesta/<int:id_encuesta>", verRespuesta, name="verRespuesta"),
    path("respuestaList/", respuestaList, name="respuestaList"),
    path("reasignar/<int:dni>", reasignar, name="reasignar"),
    path("recomendacionTable/", recomendacionTable, name="recomendacionTable"),
    path("miembrosList/", miembrosList, name="miembrosList"),
    path("reunionList/", reunionList, name="reunionList"),
    path("auditoria_detalles_miembro/<int:dni>/<int:id_auditoria>", auditoria_detalles_miembro, name="auditoria_detalles_miembro"),
    path("auditoria_detalles_reunion/<int:id>/<int:id_auditoria>", auditoria_detalles_reunion, name="auditoria_detalles_reunion"),
    path("auditoria_detalles_asistencia/<int:id_asistencia>/<int:id_auditoria>", auditoria_detalles_asistencia, name="auditoria_detalles_asistencia"),
    path("auditoria_detalles_usuario/<int:id_usuario>/<int:id_auditoria>", auditoria_detalles_usuario, name="auditoria_detalles_usuario"),
    path("estadistica_miembro/",estadistica_miembro, name="estadistica_miembro"),
    path("estadistica_reunion/",estadistica_reunion, name="estadistica_reunion"),
    path("estadistica_asistencias/",estadistica_asistencias, name="estadistica_asistencias"),
    path("filtros_estado_miembro/", filtros_estado_miembro, name="filtros_estado_miembro"),
    path("filtros_estado_reunion/", filtros_estado_reunion, name="filtros_estado_reunion"),
    path("filtros_asistencias/", filtros_asistencias, name="filtros_asistencias"),
    path("rolList/", rolList, name="rolList"),
    path("estadoList/", estadoList, name="estadoList"),
    path("enviarMensaje/", enviarMensaje, name="enviarMensaje"),
    path("editarAsistencia/<int:id_asistencia>", editarAsistencia, name="editarAsistencia"),
    path("recomendacion/", recomendacion, name="recomendacion"),
    path("listarUsuario/", listarUsuario, name="listarUsuario"),
    path('reactivarUsuario/<int:id>',reactivarUsuario, name='reactivarUsuario'),
    path('Calendario/',Calendario,name="Calendario"),
    path('configurarUsuario/<int:id>',configurarUsuario,name="configurarUsuario"),
    path('mail',mail,name="mail"),
    path('obtenerLogo',obtenerLogo,name="obtenerLogo"),
    path('cantEncuestas',cantEncuestas,name="cantEncuestas"),
]

myproject/sistema/models.py
from django.db import models
from datetime import date
from simple_history.models import HistoricalRecords
from django.core.validators import MinValueValidator

class Tipo_Reunion(models.Model):
    id_tipo_reunion =  models.AutoField(primary_key = True)
    nombre=models.CharField('Nombre (*)',max_length=200,blank = False, null = False)
    descripcion = models.CharField('Descripcion (*)',max_length=200,blank = False, null = True)
    borrado = models.BooleanField('borrado',default=False)
    frecuencia = models.IntegerField('Frecuencia (*)') #cada cuanto se va a dar este tipo de reunion
    history = HistoricalRecords()

    def __str__(self):
        return self.nombre 

class Provincia(models.Model):
    id_provincia=models.AutoField(primary_key=True)
    provincia=models.CharField('Provincia', max_length=50,blank=False,null=False)
    borrado = models.BooleanField('borrado',default=False)
    history = HistoricalRecords()
    def __str__(self):
        return self.provincia

class Localidad(models.Model):
    id_localidad = models.AutoField(primary_key = True)
    localidad=models.CharField('Localidad', max_length=50,blank=False,null=False)
    provincia=models.ForeignKey(Provincia,on_delete=models.PROTECT)
    borrado = models.BooleanField('borrado',default=False)
    history = HistoricalRecords()
    def __str__(self):
        return self.localidad

class Barrio(models.Model):
    id_barrio = models.AutoField(primary_key = True)
    barrio=models.CharField('Barrio', max_length=50,blank=False,null=False)
    localidad=models.ForeignKey(Localidad, on_delete=models.PROTECT)
    borrado = models.BooleanField('borrado',default=False)
    history = HistoricalRecords()
    def __str__(self):
        return self.barrio

class Domicilio(models.Model):
    id_domicilio = models.AutoField(primary_key=True)
    calle=models.CharField('Calle', max_length=100,blank=False,null=False)
    nro=models.CharField('Numero', max_length=50,blank=False,null=False)
    mz = models.CharField('Manzana', max_length=50,null=True,blank=True)
    departamento=models.CharField('Departamento', max_length=50,null=True,blank=True)
    piso=models.CharField('Piso', max_length=50,null=True,blank=True)
    barrio=models.ForeignKey(Barrio, on_delete=models.PROTECT)
    borrado = models.BooleanField('borrado',default=False)
    
    def __str__(self):
        return 'calle '+self.calle+'  nro '
    
class Horario_Disponible(models.Model):
    DIA=[
        ('Lunes','Lunes'),
        ('Martes','Martes'),
        ('Miercoles','Miercoles'),
        ('Jueves','Jueves'),
        ('Viernes','Viernes'),
        ('Sabado','Sabado'),
        ('Domingo','Domingo')
    ]
    id_horario_disponible=models.AutoField(primary_key=True)
    dia=models.CharField('dia',max_length=50,blank=True,null=True,choices=DIA)
    desde=models.TimeField('Desd e', auto_now=False, auto_now_add=False,null=True,blank=True)
    hasta=models.TimeField('Hasta', auto_now=False, auto_now_add=False,null=True,blank=True)
    borrado = models.BooleanField('borrado',default=False)

class Tipo_Telefono(models.Model):
    TIPO={
        ('Movil','Movil'),
        ('Fijo','Fijo')
    }
    EMPRESA={
        ('Personal','Personal'),
        ('Claro','Claro'),
        ('Movistar','Movistar'),
        ('Tuenti','Tuenti'),
        ('Otro','Otro')
    }
    id_tipo_telefono=models.AutoField(primary_key=True)
    tipo=models.CharField('Tipo', max_length=50,blank=True,null=True,choices=TIPO)
    empresa=models.CharField('Empresa', max_length=50,blank=True,null=True,choices=EMPRESA)
    borrado = models.BooleanField('borrado',default=False)

    
    def __str__(self):
        return self.tipo
    
class Telefono(models.Model):
    id_telefono=models.AutoField(primary_key=True)
    prefijo=models.IntegerField('Prefijo',blank=True,null=True)
    numero=models.IntegerField('Numero',null=True,blank=True)
    whatsapp=models.BooleanField('Whatsapp',default=True)
    tipo_telefono=models.ForeignKey(Tipo_Telefono, on_delete=models.PROTECT,null=True)
    borrado = models.BooleanField('borrado',default=False)    
    # miembro no def :C contacto= models.ForeignKey(Miembro, on_delete=models.PROTECT,null=True) #tel de contacto en caso de necesitar
    def __str__(self):
        return 'naranja'

class Estado_Civil(models.Model):
    id_estado = models.AutoField(primary_key=True)
    estado= models.CharField('soltero/a', max_length=20,blank=False, null=False)
    def __str__(self):
        return self.estado
    
class Miembro(models.Model):
    class Meta:
        unique_together = (('dni', 'sexo'),)
    SEXO=[
        ('Masculino','Masculino'),
        ('Femenino','Femenino')
    ]
    dni=models.BigIntegerField('Documento',primary_key=True)
    nombre=models.CharField('Nombre',max_length=200,blank = False, null = False)
    apellido = models.CharField('Apellido',max_length=200,blank = False, null = False)
    fecha_nacimiento = models.DateField('Fecha de Nacimiento', auto_now=False, auto_now_add=False)
    trabaja = models.BooleanField('Trabaja',default=False)
    domicilio=models.ForeignKey(Domicilio, on_delete=models.PROTECT)
    correo=models.EmailField('e-mail', max_length=100,null=True,blank=True)
    sexo =models.CharField('Sexo', max_length=20,choices=SEXO,blank=False,null=True)
    telefono=models.ForeignKey(Telefono, on_delete=models.PROTECT,null=True)
    horario_disponible=models.ManyToManyField(Horario_Disponible)
    borrado = models.BooleanField('borrado',default=False)
    estado_civil=models.ForeignKey(Estado_Civil, on_delete=models.PROTECT)
    history = HistoricalRecords()


    def __str__(self):
        return self.apellido + ', ' + self.nombre
    
    def edad(self, fecha_nacimiento):
        diferencia_fechas = date.today() - fecha_nacimiento
        diferencia_fechas_dias = diferencia_fechas.days
        edad_numerica = diferencia_fechas_dias / 365.2425
        edad = int(edad_numerica)
        return edad

class Telefono_Contacto(models.Model):
    id=models.AutoField(primary_key=True)
    miembro=models.ForeignKey(Miembro, on_delete=models.PROTECT)

class Grupo(models.Model):
    SEXO=[
        ('Masculino','Masculino'),
        ('Femenino','Femenino'),
        ('Ambos','Ambos')
    ]
    desde=models.IntegerField('Desde',blank=False,null=True,validators=[MinValueValidator(0)])
    hasta=models.IntegerField('Hasta',blank=False,null=True,validators=[MinValueValidator(0)])
    sexo=models.CharField('Sexo', max_length=20,choices=SEXO,blank=False,null=True)
    id_grupo=models.AutoField(primary_key=True)
    nombre=models.CharField('Nombre', max_length=50,blank=False,null=False)
    borrado = models.BooleanField('borrado',default=False)
    miembro=models.ManyToManyField(Miembro)
    capacidad = models.IntegerField()
    encargado=models.IntegerField('Encargado')#aca guardo el id del usuario encargado
    history = HistoricalRecords()

    def __str__(self):
        return self.nombre

class Reunion(models.Model):
    id_reunion=models.AutoField(primary_key=True)
    tipo_reunion=models.ForeignKey(Tipo_Reunion, on_delete=models.PROTECT)
    nombre =models.CharField(' Nombre (*)', max_length=100,blank=False,null=True)
    domicilio=models.ForeignKey(Domicilio,on_delete=models.PROTECT,blank=False,null=True)
    grupo=models.ForeignKey(Grupo, on_delete=models.PROTECT,null=True)
    borrado = models.BooleanField('borrado',default=False)
    horario= models.ForeignKey(Horario_Disponible, on_delete=models.CASCADE,blank=True, null=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.nombre        
    
class Asistencia(models.Model):
    id_asistencia=models.AutoField(primary_key=True)
    presente=models.BooleanField('Presente',default=False,null=True,blank=True)
    #creo que justificaciones tiene que ir aparte jiji
    miembro=models.ForeignKey(Miembro, on_delete=models.PROTECT)
    reunion=models.ForeignKey(Reunion, on_delete=models.PROTECT)
    fecha=models.DateField('Fecha', auto_now=False, auto_now_add=False)
    history = HistoricalRecords()
    justificado=models.BooleanField(null=True)

class Tipo_Pregunta(models.Model):
    id_tipo_pregunta=models.AutoField(primary_key=True)
    tipo=models.CharField('Tipo',max_length=50,blank=False,null=False)
    borrado=models.BooleanField('borrado',default=False)
    history = HistoricalRecords()
    def __str__(self):
        return self.tipo

class Pregunta(models.Model):
    id_pregunta=models.AutoField(primary_key=True)
    descripcion=models.CharField('Pregunta', max_length=200,blank=False,null=False)
    borrado = models.BooleanField('borrado',default=False,null=True)
    tipo= models.ForeignKey(Tipo_Pregunta, on_delete=models.PROTECT)
    history = HistoricalRecords()

    def __str__(self):
        return self.descripcion  

class Tipo_Encuesta(models.Model):
    id_tipo_encuesta= models.AutoField(primary_key=True)
    tipo=models.CharField("Tipo de Encuesta", max_length=50)
    cantidad = models.IntegerField('Cantidad de Faltas', null=True, blank = True)
    preguntas=models.ManyToManyField(Pregunta)
    def __str__(self):
        return self.tipo

class Encuesta(models.Model):
    id_encuesta=models.AutoField(primary_key=True)
    borrado = models.BooleanField('borrado',default=False)
    reunion=models.ForeignKey(Reunion, on_delete=models.PROTECT,null=True)
    tipo=models.ForeignKey(Tipo_Encuesta, on_delete=models.PROTECT,null=True)
    miembro = models.ForeignKey(Miembro, on_delete=models.CASCADE,null=True)
    fecha_envio=models.DateField( auto_now=False, auto_now_add=False)
    fecha_respuesta=models.DateField( auto_now=False, auto_now_add=False,null=True)
    puntaje=models.IntegerField(null=True)
    respondio=models.BooleanField(null=True)
    history = HistoricalRecords()
    def __str__(self):
        return str(self.id_encuesta)
    
class Opciones(models.Model):
    id=models.AutoField(primary_key=True)
    pregunta=models.ForeignKey(Pregunta, on_delete=models.PROTECT)

myproject/sistema/templates/sistema/agregarRespuesta.html
{% extends 'sistema/base_site.html' %}
{% block titulo %}
Responder Encuesta
{% endblock titulo %}
{% block body %}
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>

<form method="POST">
    <script>
        function myFunction(){
            var pr = $('#oculto').val();
            $.ajax({
                url: '/sistema/opcionesList',
                data: {
                    'pr': pr,
                },
                dataType: 'json',
                success: function(data) {
                    var html = "";
                    var tipo= data[0]['pregunta']['tipo'];
                    if(tipo==1){
                        $('#add').append('<div required class="row form-group"> <div class="col col-md-4"><label class=" form-control-la bel">'+data[0]['pregunta']['descripcion']+'</label></div> <textarea name="'+pr+'" id="rsp" cols="30" rows="10"></textarea></div>')
                    }
                    if(tipo==2){
                        $('#add').append('<div class="row form-group"> <div class="col col-md-4"><label class=" form-control-label">'+data[0]['pregunta']['descripcion']+'</label></div> <div class="radio" id="add-radio"></div></div>')
                        for (var i = 0; i < data.length; i++) {
                            var text = data[i].opcion;
                            $('#add-radio').append(' <input required  value="'+text+'" name="'+pr+'"type="radio"/> ' + text +'</br>' )
                        }
                        $("#add-radio").attr("id",pr);
                    }
                    if(tipo==3){
                        $('#add').append('<div class="row form-group"> <div class="col col-md-4"><label class=" form-control-label">'+data[0]['pregunta']['descripcion']+'</label></div> <div class="radio" id="add-check"></div></div>')
                        for (var i = 0; i < data.length; i++) {
                        var text = data[i].opcion;
                        $('#add-check').append('<input required  value="'+text+'" name="check[]" type="checkbox" /> ' + text + '<br />');
                        }
                    }
                }
                /*weno la idea es ponerle como name el id de la preguntita, entonces en el request.POST le llamo por ese id*/
            })
        };
    </script>
    <div class="col-lg-11">
        {% csrf_token %}
        <div class="card">
            <div class="card-header">
                <strong>Planilla para Responder </strong> Encuentas - Reunion: {{reunion.nombre}}
            </div>

            <form method="POST" class="form-horizontal">
                <div class="col col-md-12" id="add"> 
                    <select id="oculto" class="form-control selectecito" name='tipo' required>
                        {% for pregunta in preguntas %}
                            <option selected value="{{pregunta.id_pregunta}}">{{pregunta.id_pregunta}}</option>
                            <script>myFunction()</script>
                        {% endfor %}
                    </select>
                </div>

                    <div class="card">
                        <div class="card-body">
                            <button type="submit" class="btn btn-success btn-sm">Confirmar</button>
                        </div>
                    </div>
                
            </form>
        </div>
    </div>
</form>
    <script>
        $('#rango').change(function(){
            console.log($(this).val());
            //$('#rango').tooltip({'trigger':'focus', 'title': 'Password tooltip'});
        });
    </script>
    <script>
        $(document).ready(function(){
            //ordenar();
            $('#oculto').hide();
            $('#main-menu').remove(); 
            $('#left-panel').remove();
            $('#body').prop('class', "open");
        });
    </script> 
    

    
{% endblock body %}

myproject/sistema/templates/sistema/configuracion_usr.html
{% extends 'sistema/base_site.html' %}
{% load static %}
{% block titulo %}
    Configuracion de Usuario
{% endblock titulo %}
{% block body %}
    <form method="POST">
        {% csrf_token %}
        <div class="col-lg-11">
            <div class="card">
                <div class="card-header" data-step="1" data-intro="Paso 1: Bienvenido al tutorial de configuración de Usuarios">
                    <strong>Planilla de Configuracion de </strong> Usuario 
                        <a href="JavaScript:Void(0);"><i class="fa fa-question-circle" onclick="javascript:introJs().start();"></i></a>
                </div> 
                <form method="post">
                    {% if messages %}
                        <div class="col-md-11">
                        <ul class="messages">
                        {% for message in messages %}
                            <div class="alert alert-danger">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                            </div>
                        {% endfor %}
                        </ul>
                    {% endif %}    
                    <div class="card-body">
                        <div class="row form-group" data-step="2" data-intro="Paso 2: Si desea puede editar el nombre de usuario, tene en cuenta que no tiene que ser un nombre repetido">
                            <div class="col col-md-3"><label>Nombre de Usuario (*)</label></div>
                            <div class="col col-md-5">{{form.username}} </div>
                        </div>
                        <div hidden>
                            {{form.miembro}}
                        </div>
                        <div class="row form-group" data-step="3" data-intro="Paso 3: el miembro no es editable">
                            <div class="col col-md-3"><label>Miembro</label></div>
                            <div class="col col-md-5"><input disabled type="text" class="form-control" id="mb"></div>
                        </div>
                        {% if permi %}
                            <div class="row form-group">
                                <div class="col col-md-3"><label>Rol (*)</label></div>
                                <div class="col col-md-5">{{ form.rol }}</div>
                            </div>
                        {% endif %}

                        <div class="row form-group" data-step="4" data-intro="Paso 4: Este es el correo ligado al miembro, si desea puede editarlo desde la vista de editar miembro">
                            <div class="col col-md-3"><label>Correo Electronico (*)</label></div>
                            <div class="col col-md-5">{{ form.email}}</div>
                        </div>
                        {% if contra %}
                        <div class="row form-group" >
                            <div class="col col-md-3"><label>Contraseña</label></div>
                            <div class="col col-md-5"><button id="b3" class="btn btn-outline-success btn-sm" type="button" data-toggle="modal" data-target=".bs-example-modal-lg6347" data-step="5" data-intro="Paso 5: Si queres podes editar tu contraseña, hace click en el boton 'editar contraseña y rellena todos los campos, despues pone confirmar"> Cambiar Constraseña <i class="fa fa-edit"></i></button><a href="#tema1"></a></div>
                        </div>
                        
                        <form class="user" method="POST">
                            {% csrf_token %}
                            <div class="modal fade bs-example-modal-lg6347" id="myModal6347" tabindex="-1" role="dialog"
                                aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title" id="myModalLabel6347">Establecer nueva Contraseña:</h4>
                                            <button type="button" class="close" data-dismiss="modal"><span
                                                    aria-hidden="true">×</span>
                                            </button>
                                        </div>

                                        <div class="modal-body">
                                            <div class="form-row">
                                                <label for="inputAddress2" class="sub">Contraseña Actual (*)</label>
                                                <input type="password" class="form-control" name="inputPassword4"
                                                    placeholder="Contraseña Actual">
                                            </div>
                                            <br>
                                            <div class="form-row">

                                                <label for="inputAddress2" class="sub">Nueva Contraseña (*)</label>
                                                <input type="password" class="form-control" name="inputPassword6"
                                                    placeholder="Nueva Contraseña ">
                                            </div>
                                            <br>

                                            <div class="form-row">

                                                <label for="inputAddress2" class="sub">Repitir Contraseña Nueva (*)</label>
                                                <input type="password" class="form-control" name="inputPassword8"
                                                    placeholder=" Confirme Contraseña Nueva">


                                            </div>



                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                            <button type="submit" class="btn btn-primary" name="change">Confirmar</button>

                                        </div>

                                    </div>
                                </div>
                            </div>
                            <!--mmm-->
                        </form>
                        {% endif %}

                        

                        <div align="right" class="card-body" >
                            <button data-step="6" data-intro="Paso 6: Cuando termines de editar podes presionar en confirmar" type="submit" class="btn btn-primary" name="confirmar">Confirmar</button>
                        </div>
                    </div>           
                </form>
            </div>
        </div>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>

    <script>
        $(function(){
            text=$('#id_miembro option:selected').text();
            $('#mb').val(text);
            //$('#id_password1').removeAttr("required");
            //$('#id_password2').removeAttr("required");
        });
    </script>
    <script>
            $("#id_username").change(function () {
                var nombre = $(this).val();
                console.log("oli");
                $.ajax({
                    url: '{% url "validarNombre" %}',
                    data: {
                        'nombre': nombre
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data.is_taken) {
                            $("#id_username").val('')
                            alert(data['error_message'] );
                        }
                    }
                });
            });
    </script>
{% endblock body %}